;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ignore
        keyboard-escape-quit
        mc/unmark-previous-like-this-word
        mouse-drag-mode-line
        mouse-select-window
        ultra-scroll
        ))

(setq mc/cmds-to-run-once
      '(
        ))
